### PR TITLE
Add output flag

### PR DESCRIPTION
**Pull request by ruangustavo**
Hey! What's up? As the name suggests, it adds the feature of defining the output file name. Also, it handles possible invalid filename errors.

### CODE REVIEW

**Comment by akiomik** [comment]
Wow great!

**Comment by ruangustavo** [comment]
> Wow great!

Thanks 😃

**Comment by ruangustavo** [comment]
By the way, are you going to merge it? 😅

**Comment by akiomik** [comment]
Yes, I'll merge when I've verified that it works. Is there any reason I should rush the merge?

**Comment by ruangustavo** [comment]
> Yes, I'll merge when I've verified that it works. Is there any reason I should rush the merge?

No and sorry if it sounded like that. It was just an innocent question.

**Pull request closed without merging**
